### ISSUE TITLE
FtHoF doesn't count Chime and Seasons

### ISSUE THREAD

**Issue by Zombato** [Mtarnuhal/FrozenCookies#19]
FtHoF always display next GC just for normal conditions. But enabling Chime sound or/and having two specific seasons change the order/spells. So it should be somehow fixed.

More details here: http://fthof-planner.s3-website.us-east-2.amazonaws.com/

**Comment by shrx** [comment]
Yeah I came here to report this.

**Comment by adavidw** [comment]
Turns out that Chime doesn't affect the spell anymore, as of version 2.028. At this point the only thing affecting the spell is those two seasons, and it looks like those are being accounted for in the code. I tested it myself just now, comparing to the FtHoF-planner listed above, and comparing to what cookies are actually being cast. It looks like it's operating correctly, so I'm going to close this one.

**Comment by shrx** [comment]
Thanks for looking into this :)
