### ISSUE TITLE
error with character format

### ISSUE THREAD

**Issue by Vaquicraft** [Mtarnuhal/FrozenCookies#69]
![image](https://user-images.githubusercontent.com/36343149/102211716-4d8ce400-3ed4-11eb-8d56-6c882388ba01.png)

Hello.

As you can see in the screenshot, the french character "é" of "sablés" is not working correctly at the left-bottom of the screen.

**Comment by Mtarnuhal** [comment]
Thanks for reporting this issue. Already have an idea what is causing this.
Probably we have to add a javascript decode.
`function decodeHtml(html) {
    var txt = document.createElement("textarea");
    txt.innerHTML = html;
    return txt.value;
}`
What do you think @adavidw

**Comment by adavidw** [comment]
I've never noticed that myself, which means that sablés probably came and went  on my run-throughs before I ever saw it.

What about the recommendation list? Does it show correctly there?

**Comment by adavidw** [comment]
Actually, I just changed one of the building names to "sablés" and that appears to show correctly. Maybe it's different when it's the actual sablés item, so I'll try to get a different run-through to get that.

But, is it possible the problem is somewhere else? @Vaquicraft can you determine what encoding your browser is set to?

<img width="365" alt="image" src="https://user-images.githubusercontent.com/6272278/102244851-14477a80-3eba-11eb-808e-1171efdf3a28.png">

**Comment by adavidw** [comment]
Nevermind, when I go through and get to the actual "sablés", I can reproduce. Attached is a save file reproducing the issue that we can use for testing.
[FancyPortalBakery.txt](https://github.com/Mtarnuhal/FrozenCookies/files/5697687/FancyPortalBakery.txt)
